#!/usr/bin/env node
/**
 * migrate-serve.mjs — Source-side migration orchestrator (Gap 8 simplification, Option D)
 *
 * Turns the 10-step manual migration into 2 commands:
 *   SOURCE: node migrate-serve.mjs [--output-dir <dir>] [--role primary|worker] ...
 *   TARGET: curl -fsSL http://<source-ip>:18790/install/<token> | bash
 *
 * Flow:
 *   1. Run exportMigrateBundle() (existing, unchanged crypto/bundle format)
 *   2. Generate a per-session install script (embedded checksum + token + URL
 *      + pinned openclaw version — NEVER @latest, David 2026-08-31)
 *   3. Spawn agent-download-server.mjs with --install-script + --scripts-dir
 *   4. Print the one-line curl command for the target machine
 *   5. Keep the bundle on source after download (David decision 2: source
 *      bundle is the backup if import fails; delete manually)
 *
 * The server shuts down after bundle download or 15 min (existing behavior).
 */

import { spawn } from 'node:child_process';
import { existsSync, writeFileSync, mkdtempSync, rmSync, readFileSync, statSync } from 'node:fs';
import { join, dirname, resolve, basename } from 'node:path';
import { tmpdir, hostname, networkInterfaces, homedir } from 'node:os';
import { randomUUID, createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const PORT = 18790;

// ── Exported for tests ───────────────────────────────────────────

/**
 * Detect the best LAN IP for the source host (first non-internal IPv4).
 */
export function detectLanIp() {
  const nets = networkInterfaces();
  for ( const list of Object.values( nets ) ) {
    for ( const n of list || [] ) {
      if ( n.family === 'IPv4' && !n.internal ) return n.address;
    }
  }
  return '127.0.0.1';
}

/**
 * Generate the per-session target-side install script.
 * SECURITY: passphrase is NEVER embedded — prompted on the target via /dev/tty.
 * @param {object} o
 * @param {string} o.serverUrl   e.g. http://192.0.2.1:18790  (RFC 5737 doc range)
 * @param {string} o.token       single-use download token (UUIDv4)
 * URL + token identify one session; checksum binds script to ONE bundle.
 * @param {string} o.checksumHex    SHA-256 of the encrypted bundle (out-of-band value)
 * @param {string} o.bundleName      e.g. migrate-bundle-202608311430.tar.gz.enc
 * @param {string} o.openclawPin     e.g. 2026.7.1-2 (NEVER 'latest')
 * @param {number} o.bundleSize   bytes (for progress display)
 * @param {object} [o.scriptChecksums] name → sha256hex for the three served
 *        helper scripts (Grok R3 fix: verify over plain HTTP before executing).
 */
export function generateInstallScript({ serverUrl, token, checksumHex, bundleName, openclawPin, bundleSize, scriptChecksums = {} }) {
  const sizeMb = ( bundleSize / 1024 / 1024 ).toFixed(1);
  // Placeholder tokens (not JS template interpolation) so shell ${VAR} refs
  // survive as literal text. Every generated script is bound to ONE session:
  // URL + token + checksum identify exactly one bundle.
  const tmpl = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    '# ── BuddyBots Migration Installer (generated by migrate-serve.mjs) ──',
    '# Server: __SERVER_URL__',
    '# Bundle: __BUNDLE_NAME__ (__BUNDLE_SIZE_MB__ MB)',
    '# One session = one bundle = one checksum. Do not reuse this script.',
    '',
    // Single quotes = injection-safe embedding: $ ` " are literal inside
    // single quotes (Grok R1 S-2). Values are UUID/hex/URL/version strings —
    // a literal single quote cannot occur; assertNoQuote guard in runServe.
    "BUNDLE_SHA256='__CHECKSUM_HEX__'",
    "SERVER_URL='__SERVER_URL__'",
    "TOKEN='__TOKEN__'",
    "BUNDLE_NAME='__BUNDLE_NAME__'",
    "OPENCLAW_PIN='__OPENCLAW_PIN__'",
    'WORKDIR="$(mktemp -d /tmp/buddy-migrate.XXXXXX)"',
    "trap 'rm -rf \"$WORKDIR\"' EXIT",
    '',
    "say() { printf '\\033[1;32m==>%s\\033[0m\\n' \" $1\"; }",
    "die() { printf '\\033[1;31mERROR:%s\\033[0m\\n' \" $1\" >&2; exit 1; }",
    '',
    '# ── 1. Detect OS/arch ────────────────────────────────────────────',
    'OS="$(uname -s)"; ARCH="$(uname -m)"',
    'say "Target: $OS $ARCH"',
    '',
    '# ── 2. Download import scripts FIRST — the bundle download ends the server ──',
    'say "Downloading import scripts…"',
    'curl -fsSL -o "$WORKDIR/migrate-import.mjs" "$SERVER_URL/scripts/migrate-import.mjs?token=$TOKEN" || die "import script download failed"',
    'curl -fsSL -o "$WORKDIR/migrate-export.mjs" "$SERVER_URL/scripts/migrate-export.mjs?token=$TOKEN" || die "export script download failed (crypto dependency)"',
    'curl -fsSL -o "$WORKDIR/paths.mjs" "$SERVER_URL/scripts/paths.mjs?token=$TOKEN" || die "paths.mjs download failed (path constants)"',
    '',
    '# ── 2b. Verify script checksums BEFORE execution (plain HTTP is untrusted — Grok R3) ──',
    'hash_of() { sha256sum "$1" 2>/dev/null | awk \'{print $1}\' || shasum -a 256 "$1" | awk \'{print $1}\'; }',
    'check_script() { local name="$1" want="$2" got; got="$(hash_of "$WORKDIR/$name")";',
    '  [ "$got" = "$want" ] || die "$name checksum MISMATCH (got ${got:0:12}…, want ${want:0:12}…) — do NOT run tampered scripts"; }',
    "check_script migrate-import.mjs '__SCRIPT_SHA_IMPORT__'",
    "check_script migrate-export.mjs '__SCRIPT_SHA_EXPORT__'",
    "check_script paths.mjs '__SCRIPT_SHA_PATHS__'",
    'say "Import scripts verified."',
    '',
    '# ── 3. Download the bundle (single-use token — LAST fetch: server exits after) ──',
    'say "Downloading bundle $BUNDLE_NAME…"',
    'curl -fsSL -o "$WORKDIR/$BUNDLE_NAME" "$SERVER_URL/$TOKEN/$BUNDLE_NAME" \\',
    '  || die "download failed — is the source server still up? (15-min timeout, single use)"',
    'say "Bundle downloaded."',
    '',
    '# ── 4. Verify SHA-256 (out-of-band checksum gate: same value the source printed) ──',
    'say "Verifying checksum…"',
    'ACTUAL="$(sha256sum "$WORKDIR/$BUNDLE_NAME" 2>/dev/null | awk \'{print $1}\' || shasum -a 256 "$WORKDIR/$BUNDLE_NAME" | awk \'{print $1}\')"',
    '[ "$ACTUAL" = "$BUNDLE_SHA256" ] || die "checksum MISMATCH — bundle tampered or truncated; do not import"',
    'say "Checksum OK."',
    '',
    '# ── 5. Install Node.js ≥22 if absent or too old (existence ≠ version) ──',
    'NODE_MAJOR=0',
    'if command -v node >/dev/null 2>&1; then',
    '  NODE_MAJOR="$(node --version 2>/dev/null | sed \'s/^v//; s/\\..*//\')"',
    'fi',
    'if [ "${NODE_MAJOR:-0}" -lt 22 ]; then',
    '  say "Installing Node.js ≥22 (found: ${NODE_MAJOR:-none})…"',
    '  if [ "$OS" = "Darwin" ]; then',
    '    command -v brew >/dev/null 2>&1 || die "Homebrew missing — install from https://brew.sh then re-run"',
    '    brew install node',
    '  elif command -v apt-get >/dev/null 2>&1; then',
    '    # NodeSource + sudo (David approved 2026-08-31, Grok R1 fix)',
    '    curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash -',
    '    sudo apt-get update',
    '    sudo apt-get install -y nodejs',
    '  elif command -v dnf >/dev/null 2>&1; then',
    '    curl -fsSL https://rpm.nodesource.com/setup_22.x | sudo bash -',
    '    sudo dnf makecache',
    '    sudo dnf install -y nodejs',
    '  else',
    '    die "Unsupported package manager — install Node.js ≥22 manually, then re-run"',
    '  fi',
    'fi',
    'say "Node.js $(node --version)."',
    '',
    '# ── 6. Install PINNED OpenClaw (never @latest — 8.1.x unstable for this setup) ──',
    'say "Installing openclaw@$OPENCLAW_PIN…"',
    '# Prefer user/global npm first; elevate only if needed (keeps real errors visible)',
    'npm install -g "openclaw@$OPENCLAW_PIN" || sudo npm install -g "openclaw@$OPENCLAW_PIN"',
    '',
    '# ── 7. Passphrase (NEVER argv — read from tty) ───────────────────',
    'say "Enter the migration passphrase (set by the source operator):"',
    'IFS= read -rs PASSPHRASE < /dev/tty',
    '[ "${#PASSPHRASE}" -ge 16 ] || die "passphrase too short (min 16 chars)"',
    'export MIGRATE_PASSPHRASE="$PASSPHRASE"',
    'unset PASSPHRASE',
    '',
    '# ── 8. Import ────────────────────────────────────────────────────',
    'say "Importing bundle…"',
    'node "$WORKDIR/migrate-import.mjs" \\',
    '  --import "$WORKDIR/$BUNDLE_NAME" \\',
    '  --expected-checksum "$BUNDLE_SHA256"',
    '',
    '# ── 9. Start gateway (David approved auto-start 2026-08-31) ──────',
    'say "Starting OpenClaw gateway…"',
    'openclaw gateway start || say "gateway start returned non-zero — run openclaw gateway status to check"',
    '',
    '# ── 10. Next steps ───────────────────────────────────────────────',
    'say "Import complete."',
    'cat <<\'EOF\'',
    'Remaining manual steps:',
    '  1. Signal: relink separately (one number per instance).',
    '  2. Linux targets: keychain secrets need manual restore (macOS-only format).',
    '  3. Cron jobs: staged at ~/.openclaw/pending-cron-import.json — your agent',
    '     creates each via the cron tool (gateway API, never SQL).',
    '  4. Send your agent a test message to verify.',
    '  5. The downloaded bundle lives in a temp dir cleaned on exit (trap).',
    'EOF',
    '',
  ].join('\n');
  // Assert no single quotes in embedded values (injection guard for single-quote embedding)
  const embedded = { serverUrl, token, checksumHex, bundleName, openclawPin, ...scriptChecksums };
  for ( const [ k, v ] of Object.entries( embedded ) ) {
    if ( typeof v === 'string' && v.includes("'") ) {
      throw new Error( `Refusing to generate install script: ${k} contains a single quote (injection risk)` );
    }
  }
  return tmpl
    .replaceAll('__SERVER_URL__', serverUrl)
    .replaceAll('__CHECKSUM_HEX__', checksumHex)
    .replaceAll('__TOKEN__', token)
    .replaceAll('__BUNDLE_NAME__', bundleName)
    .replaceAll('__OPENCLAW_PIN__', openclawPin)
    .replaceAll('__BUNDLE_SIZE_MB__', sizeMb)
    .replaceAll('__SCRIPT_SHA_IMPORT__', scriptChecksums['migrate-import.mjs'] || '')
    .replaceAll('__SCRIPT_SHA_EXPORT__', scriptChecksums['migrate-export.mjs'] || '')
    .replaceAll('__SCRIPT_SHA_PATHS__', scriptChecksums['paths.mjs'] || '');
}

/**
 * Run the full serve flow: export → generate script → spawn server → print curl.
 * Returns after export+setup; the server child runs until download/timeout.
 */
export async function runServe(options = {}) {
  const { exportMigrateBundle, probeOpenclawVersion } = await import('./migrate-export.mjs');

  // --no-serve / --dry-run: export only, do not start the download server
  // (Grok R2 + Claude Stage4 R1: dry-run has no outputPath and would crash)
  if (options.noServe || options.dryRun) {
    return await exportMigrateBundle(options);
  }

  const token = options.token || randomUUID();
  const lanIp = options.lanIp || detectLanIp();
  const serverUrl = options.serverUrl || `http://${lanIp}:${PORT}`;
  const outDir = options.outputDir || join(homedir(), 'Documents');
  const openclawPin = options.openclawPin || probeOpenclawVersion();

  // Export (passphrase comes from MIGRATE_PASSPHRASE env or options)
  const res = await exportMigrateBundle({
    ...options,
    output: options.output || join(outDir, `migrate-bundle-${new Date().toISOString().replace(/[-:T]/g, '').slice(0, 12)}.tar.gz.enc`),
  });

  const script = generateInstallScript({
    serverUrl,
    token,
    checksumHex: res.bundleChecksum,
    bundleName: basename(res.outputPath),
    openclawPin,
    bundleSize: statSync(res.outputPath).size,
    // Grok R3 fix: bind the served helper scripts to known hashes so a
    // plain-HTTP attacker cannot swap the import code before it runs.
    scriptChecksums: {
      'migrate-import.mjs': sha256OfFile(join(__dirname, 'migrate-import.mjs')),
      'migrate-export.mjs': sha256OfFile(join(__dirname, 'migrate-export.mjs')),
      'paths.mjs': sha256OfFile(join(__dirname, 'paths.mjs')),
    },
  });

  // Write install script to a temp file the server will serve
  const scriptDir = mkdtempSync(join(tmpdir(), 'mig-serve-'));
  const scriptPath = join(scriptDir, 'install.sh');
  writeFileSync(scriptPath, script, { mode: 0o644 });

  console.log('┌──────────────────────────────────────────────────────────────');
  console.log('│ BuddyBots Migration — source serving on :18790');
  console.log(`│ Bundle: ${res.outputPath}`);
  console.log(`│ Size: ${( statSync(res.outputPath).size / 1024 / 1024 ).toFixed(1)} MB · SHA-256: ${res.bundleChecksum.slice(0, 12)}…`);
  console.log('│');
  console.log('│ On the TARGET machine, run:');
  console.log(`│   curl -fsSL ${serverUrl}/install/${token} | bash`);
  console.log('│');
  console.log('│ The server closes after the bundle is downloaded or 15 minutes.');
  console.log('│ The bundle is KEPT on this machine (backup if import fails).');
  console.log('└──────────────────────────────────────────────────────────────');

  const child = spawn(process.execPath, [
    join(__dirname, 'agent-download-server.mjs'),
    '--token', token,
    '--file', res.outputPath,
    '--install-script', scriptPath,
    '--scripts-dir', join(__dirname),
    '--keep-archive',
  ], { stdio: 'inherit' });

  child.on('exit', ( code ) => {
    rmSync(scriptDir, { recursive: true, force: true });
    process.exit( code ?? 0 );
  });

  return { token, serverUrl, bundlePath: res.outputPath, bundleChecksum: res.bundleChecksum, child };
}

// ── CLI ──────────────────────────────────────────────────────────

function sha256OfFile(p) {
  return createHash('sha256').update(readFileSync(p)).digest('hex');
}

function parseArgs(argv) {
  const args = { output: null, outputDir: null, passphrase: null, role: 'primary',
    cronsFile: null, keychainServices: [], targetPlatform: null, dryRun: false, noServe: false, help: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const val = () => { if (i + 1 >= argv.length) { console.error(`❌ ${a} requires a value`); process.exit(1); } return argv[++i]; };
    switch (a) {
      case '--output': args.output = val(); break;
      case '--output-dir': args.outputDir = val(); break;
      case '--passphrase': args.passphrase = val(); break;
      case '--role': args.role = val(); break;
      case '--crons': args.cronsFile = val(); break;
      case '--target-platform': args.targetPlatform = val(); break;
      case '--keychain-service': args.keychainServices.push(val()); break;
      case '--dry-run': args.dryRun = true; break;
      case '--no-serve': args.noServe = true; break;
      case '--help': args.help = true; break;
      default: console.error(`❌ Unknown flag: ${a}`); process.exit(1);
    }
  }
  return args;
}

if (process.argv[1]?.endsWith('migrate-serve.mjs')) {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log(`migrate-serve — Source-Served Migration (Option D)

Usage:
  node migrate-serve.mjs [--output-dir <dir>] [--role primary|worker] ...

Flags: (same as migrate-export.mjs, plus)
  --no-serve       Export only — do not start the download server
  --output-dir <dir>  Where the bundle lands (default ~/Documents)

After export, this prints the target command:
  curl -fsSL http://<lan-ip>:18790/install/<token> | bash`);
    process.exit(0);
  }
  runServe(args).catch(err => {
    console.error(`❌ ${err.message}`);
    process.exit(1);
  });
}
